package au.com.telstra.team;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "BusinessRequirement")
public class BusinessRequirement implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "BUSINESSREQUIREMENT_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "BUSINESSREQUIREMENT_ID_GENERATOR", sequenceName = "BUSINESSREQUIREMENT_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("BusinessJustification")
	private java.lang.String businessJustification;

	@javax.persistence.Column(name = "documents")
	@javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Label("Documents")
	private java.util.List<java.lang.String> documents;

	public BusinessRequirement() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getBusinessJustification() {
		return this.businessJustification;
	}

	public void setBusinessJustification(java.lang.String businessJustification) {
		this.businessJustification = businessJustification;
	}

	public java.util.List<java.lang.String> getDocuments() {
		return this.documents;
	}

	public void setDocuments(java.util.List<java.lang.String> documents) {
		this.documents = documents;
	}

	public BusinessRequirement(java.lang.Long id,
			java.lang.String businessJustification,
			java.util.List<java.lang.String> documents) {
		this.id = id;
		this.businessJustification = businessJustification;
		this.documents = documents;
	}

}