package au.com.telstra.team;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "financialdetail")
public class FinancialDetail implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "FINANCIALDETAIL_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "FINANCIALDETAIL_ID_GENERATOR", sequenceName = "FINANCIALDETAIL_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("EstimateTableComment")
	private java.lang.String estimateTableComment;

	@org.kie.api.definition.type.Label("FundingCategory")
	private java.lang.String fundingCategory;

	@org.kie.api.definition.type.Label("FundingType")
	private java.lang.String fundingType;

	@org.kie.api.definition.type.Label("FundingRequiredByDate")
	private java.lang.String fundingRequiredByDate;

	@org.kie.api.definition.type.Label("FundingComments")
	private java.lang.String fundingComments;

	@javax.persistence.Column(name = "estimate")
	@javax.persistence.OneToMany(orphanRemoval = false, cascade = {
			javax.persistence.CascadeType.ALL,
			javax.persistence.CascadeType.PERSIST}, fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Label("Estimate")
	private java.util.List<au.com.telstra.team.Estimate> estimate;

	public FinancialDetail() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getEstimateTableComment() {
		return this.estimateTableComment;
	}

	public void setEstimateTableComment(java.lang.String estimateTableComment) {
		this.estimateTableComment = estimateTableComment;
	}

	public java.lang.String getFundingCategory() {
		return this.fundingCategory;
	}

	public void setFundingCategory(java.lang.String fundingCategory) {
		this.fundingCategory = fundingCategory;
	}

	public java.lang.String getFundingType() {
		return this.fundingType;
	}

	public void setFundingType(java.lang.String fundingType) {
		this.fundingType = fundingType;
	}

	public java.lang.String getFundingRequiredByDate() {
		return this.fundingRequiredByDate;
	}

	public void setFundingRequiredByDate(java.lang.String fundingRequiredByDate) {
		this.fundingRequiredByDate = fundingRequiredByDate;
	}

	public java.lang.String getFundingComments() {
		return this.fundingComments;
	}

	public void setFundingComments(java.lang.String fundingComments) {
		this.fundingComments = fundingComments;
	}

	public java.util.List<au.com.telstra.team.Estimate> getEstimate() {
		return this.estimate;
	}

	public void setEstimate(
			java.util.List<au.com.telstra.team.Estimate> estimate) {
		this.estimate = estimate;
	}

	public FinancialDetail(java.lang.Long id,
			java.lang.String estimateTableComment,
			java.lang.String fundingCategory, java.lang.String fundingType,
			java.lang.String fundingRequiredByDate,
			java.lang.String fundingComments,
			java.util.List<au.com.telstra.team.Estimate> estimate) {
		this.id = id;
		this.estimateTableComment = estimateTableComment;
		this.fundingCategory = fundingCategory;
		this.fundingType = fundingType;
		this.fundingRequiredByDate = fundingRequiredByDate;
		this.fundingComments = fundingComments;
		this.estimate = estimate;
	}

}