package au.com.telstra.team;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Location implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "LOCATION_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "LOCATION_ID_GENERATOR", sequenceName = "LOCATION_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "Latitude")
	private java.lang.String latitude;

	@org.kie.api.definition.type.Label(value = "Longitude")
	private java.lang.String longitude;

	public Location() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(java.lang.String latitude) {
		this.latitude = latitude;
	}

	public java.lang.String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(java.lang.String longitude) {
		this.longitude = longitude;
	}

	public Location(java.lang.Long id, java.lang.String latitude,
			java.lang.String longitude) {
		this.id = id;
		this.latitude = latitude;
		this.longitude = longitude;
	}

}