package au.com.telstra.team;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Site implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "SITE_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "SITE_ID_GENERATOR", sequenceName = "SITE_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("AreaType")
	private java.lang.String areaType;

	@org.kie.api.definition.type.Label("Technology")
	@javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
	private java.util.List<java.lang.String> technology;

	@org.kie.api.definition.type.Label("SiteType")
	private java.lang.String siteType;

	@org.kie.api.definition.type.Label("SectorCount")
	private java.lang.String sectorCount;

	@org.kie.api.definition.type.Label("SiteComments")
	private java.lang.String siteComments;

	@org.kie.api.definition.type.Label(value = "SiteName")
	private java.lang.String siteName;

	public Site() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getAreaType() {
		return this.areaType;
	}

	public void setAreaType(java.lang.String areaType) {
		this.areaType = areaType;
	}

	public java.util.List<java.lang.String> getTechnology() {
		return this.technology;
	}

	public void setTechnology(java.util.List<java.lang.String> technology) {
		this.technology = technology;
	}

	public java.lang.String getSiteType() {
		return this.siteType;
	}

	public void setSiteType(java.lang.String siteType) {
		this.siteType = siteType;
	}

	public java.lang.String getSectorCount() {
		return this.sectorCount;
	}

	public void setSectorCount(java.lang.String sectorCount) {
		this.sectorCount = sectorCount;
	}

	public java.lang.String getSiteComments() {
		return this.siteComments;
	}

	public void setSiteComments(java.lang.String siteComments) {
		this.siteComments = siteComments;
	}

	public java.lang.String getSiteName() {
		return this.siteName;
	}

	public void setSiteName(java.lang.String siteName) {
		this.siteName = siteName;
	}

	public Site(java.lang.Long id, java.lang.String areaType,
			java.util.List<java.lang.String> technology,
			java.lang.String siteType, java.lang.String sectorCount,
			java.lang.String siteComments, java.lang.String siteName) {
		this.id = id;
		this.areaType = areaType;
		this.technology = technology;
		this.siteType = siteType;
		this.sectorCount = sectorCount;
		this.siteComments = siteComments;
		this.siteName = siteName;
	}

}